services:
  kafka:
    image: sha256:778f64413532f180148569116b3f5d734e7f1c0cdee650b984f88fd97a20a4f9
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 10s
      retries: 5

  init-kafka:
    image: confluentinc/cp-kafka:7.8.6
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c " kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic orders --partitions 6 --replication-factor 1 && kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic orders-dlq --partitions 3 --replication-factor 1 "

  producer:
    build: .
    depends_on:
      init-kafka:
        condition: service_completed_successfully
    command: python producer/producer.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  tracker:
    build: .
    depends_on:
      init-kafka:
        condition: service_completed_successfully
    command: python services/order_tracker/tracker.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  inventory:
    build: .
    depends_on:
      init-kafka:
        condition: service_completed_successfully
    command: python services/inventory/inventory.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  analytics:
    build: .
    depends_on:
      init-kafka:
        condition: service_completed_successfully
    command: python services/analytics/analytics.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  dlq-logger:
    build: .
    depends_on:
      init-kafka:
        condition: service_completed_successfully
    command: python services/dlq/dlq_logger.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
